language: java
sudo: true
dist: trusty
jdk: oraclejdk9



addons:
  postgresql: "12"

  apt:
      packages:
      - oracle-java9-installer
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5432
    - PGUSER=postgre

before_install:
    - chmod +x mvnw

script : ./mvnw clean install
