dist: xenial
sudo: required
language: java

before_script:
  - psql -c 'create database GIVEMEAHAND' -U postgres

before_install:

  - chmod +x mvnw
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-13 postgresql-client-13
  - sudo service postgresql restart 13


env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

script:
    - psql -c "SELECT version();"
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
