language: java
sudo: true
dist: trusty
jdk: oraclejdk9

addons:
  postgresql: '13'

  apt:
      packages:
        - postgresql-11
        - postgresql-client-11



before_install:
    - chmod +x mvnw
    - sudo sed -i -e 's/^#listen_addresses.*/listen_addresses = "*"/' /etc/postgresql/13/main/postgresql.conf
    - sudo sed -i -e 's/^port = 5433/port = 5432/' /etc/postgresql/13/main/postgresql.conf
    - sudo service postgresql restart 13
script : ./mvnw clean install
