language: java
sudo: required
dist: trusty
jdk: oraclejdk9
services:
  - postgresql
addons:
  postgresql: "13"
  apt:
      packages:
        - postgresql-13
        - postgresql-client-13

env:
  global:
    - PGPORT=5432
before_install:
  - chmod +x mvnw
    - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/13/main/postgresql.conf
    - sudo cp /etc/postgresql/{9.3,13}/main/pg_hba.conf
    - sudo pg_ctlcluster 13 main restart


before_script:
  - sudo psql -p 5432 -U postgres -c 'create database GIVEMEAHAND;'
script : ./mvnw clean install
