language: java
sudo: required
dist: trusty
jdk: oraclejdk9
addons:
  postgresql: "13"
  apt:
      update: true
      packages:
      - postgresql-13
      - postgresql-13-postgis-3
      - oracle-java9-installer

env:
  global:
    - PGPORT=5432
before_install:
  - chmod +x mvnw
  - # Use trust instead of peer authentication:
    - >-
      sudo sed -i
      -e '/local.*peer/s/postgres/all/'
      -e 's/peer\|md5/trust/g'
      /etc/postgresql/13/main/pg_hba.conf
    # Restart the PostgreSQL service:
    - sudo service postgresql@13-main restart


before_script:
  - sudo psql -p 5432 -U postgres -c 'create database GIVEMEAHAND;'
script : ./mvnw clean install
