language: java
sudo: true
dist: focal
jdk: oraclejdk9

services:
  - postgresql
script :
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  ./mvnw clean install

before_install:
    - chmod +x mvnw

