language: java
sudo: required
dist: trusty
jdk: oraclejdk9

addons:
  apt:
    sources:
      - precise-pgdg-13
      packages:
        - postgresql-13
        - postgresql-contrib-13
      postgresql: 13

env:
  global:
    - PGPORT=5432
before_script:
:
  - sudo cp /etc/postgresql/9.3/main/pg_hba.conf /etc/postgresql/13/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'create database "GIVEMEAHAND";'
  - psql -U postgres travis-db-test -c 'create extension "uuid-ossp";

script : ./mvnw clean install
