language: java
sudo: required
dist: xenial
jdk: oraclejdk9

addons:
  apt:
      packages:

      - oracle-java9-installer


before_install:
  - chmod +x mvnw
  - sudo service postgresql stop
    - sudo apt-get --yes remove postgresql-9.3
    - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-13-postgis-2.5-scripts postgresql-13 postgresql-client-13 postgresql-13-postgis-2.5
    - sed -e 's/^port.*/port = 5432/' /etc/postgresql/13/main/postgresql.conf > postgresql.conf
    - sudo chown postgres postgresql.conf
    - sudo mv postgresql.conf /etc/postgresql/11/main
    - sudo cp /etc/postgresql/{9.3,13}/main/pg_hba.conf
    - sudo service postgresql restart 13
script : ./mvnw clean install
