language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  postgresql: "13"

  apt:
    packages:
      - oracle-java9-installer
      - postgresql-13
      - postgresql-client-13
before_install:
  - chmod +x mvnw
script : ./mvnw clean install
