language: java
sudo: required
dist: trusty
jdk: oraclejdk9
addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13
      - oracle-java9-installer

env:
  global:
    - PGPORT=5432
    - PGUSER=postgre

before_install:
    - chmod +x mvnw
      - sudo /etc/init.d/postgresql stop
      - sudo apt-get -y remove --purge postgresql-9.1
      - sudo apt-get -y remove --purge postgresql-9.2
      - sudo apt-get -y remove --purge postgresql-9.3
      - sudo apt-get -y remove --purge postgresql-9.4
      - sudo apt-get -y autoremove
      - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
      - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
      - sudo apt-get update
      - sudo apt-get -y install postgresql-13
      - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/13/main/pg_hba.conf'
      - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/13/main/pg_hba.conf'
      - sudo /etc/init.d/postgresql restart
      - psql --version

before_script:
  - psql -c 'create database GIVEMEAHAND;' -U postgres
script : ./mvnw clean install
