language: java
sudo: true
dist: trusty
jdk: oraclejdk9

services:
  - postgresql

addons:

  apt:
      packages:
      - oracle-java9-installer

env:
  global:
    - PGPORT=5432
    - PGUSER=postgre

before_install:
    - chmod +x mvnw
    - sudo apt-get update
    - sudo /etc/init.d/postgresql stop
    - sudo /etc/init.d/postgresql start 12

script : ./mvnw clean install
