dist: xenial
sudo: required
language: java

before_script:
  - psql -c 'GIVEMEAHAND' -U postgres

before_install:


env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

script:
  - psql --version
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
